[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["testgql"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "testgql"
  org = "kajendranalagaratnam"
  version = "1.0.1"

